// <auto-generated />
using FinalMovieReview.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalMovieReview.Server.Migrations
{
    [DbContext(typeof(FinalMovieReviewServerContext))]
    [Migration("20230612070235_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalMovieReview.Shared.Model.MData", b =>
                {
                    b.Property<string>("MovieName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MovieDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("MovieRating")
                        .HasColumnType("real");

                    b.HasKey("MovieName");

                    b.ToTable("MData");
                });

            modelBuilder.Entity("FinalMovieReview.Shared.Model.MReviews", b =>
                {
                    b.Property<int>("user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user"));

                    b.Property<string>("MDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("MRating")
                        .HasColumnType("real");

                    b.HasKey("user");

                    b.ToTable("MReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
